// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RendaVariavelApi.Data;

#nullable disable

namespace RendaVariavelApi.Migrations
{
    [DbContext(typeof(RendaVariavelDbContext))]
    [Migration("20240409003955_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RendaVariavelApi.Models.Cotacao", b =>
                {
                    b.Property<int>("IdCotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DIVIDENDO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCotacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DATA_COTACAO");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TICKER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("IdCotacao");

                    b.ToTable("COTACOES", (string)null);
                });

            modelBuilder.Entity("RendaVariavelApi.Models.Dividendo", b =>
                {
                    b.Property<int>("IdDividendo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DIVIDENDO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDividendo"));

                    b.Property<DateTime>("DataCom")
                        .HasColumnType("date")
                        .HasColumnName("DATA_COM");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("DATA_PAGAMENTO");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TICKER");

                    b.Property<int>("TipoDividendo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_DIVIDENDO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("IdDividendo");

                    b.ToTable("DIVIDENDOS", (string)null);
                });

            modelBuilder.Entity("RendaVariavelApi.Models.FundoImobiliario", b =>
                {
                    b.Property<int>("IdFundoImobiliario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FUNDO_IMOBILIARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFundoImobiliario"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<int?>("CotasEmitidas")
                        .HasColumnType("int")
                        .HasColumnName("COTAS_EMITIDAS");

                    b.Property<string>("Mandato")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MANDATO");

                    b.Property<int?>("NumeroDeCotistas")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_COTISTAS");

                    b.Property<string>("PrazoDeDuracao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRAZO_DURACAO");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PUBLICO_ALVO");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("Segmento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SEGMENTO");

                    b.Property<double?>("TaxaDeAdministracao")
                        .HasColumnType("float")
                        .HasColumnName("TAXA_ADMINISTRACAO");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TICKER");

                    b.Property<string>("TipoDeFundo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TIPO_FUNDO");

                    b.Property<string>("TipoDeGestao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TIPO_GESTAO");

                    b.Property<int>("TipoInvestimento")
                        .HasColumnType("int")
                        .HasColumnName("TIPO_INVESTIMENTO");

                    b.Property<double?>("UltimoRendimento")
                        .HasColumnType("float")
                        .HasColumnName("ULTIMO_RENDIMENTO");

                    b.Property<double?>("Vacancia")
                        .HasColumnType("float")
                        .HasColumnName("VACANCIA");

                    b.Property<double?>("ValorPatrimonial")
                        .HasColumnType("float")
                        .HasColumnName("VALOR_PATRIMONIAL");

                    b.Property<double?>("ValorPatrimonialPorCota")
                        .HasColumnType("float")
                        .HasColumnName("VALOR_PATRIMONIAL_POR_COTA");

                    b.HasKey("IdFundoImobiliario");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("FUNDOS_IMOBILIARIOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
